### ISSUE TITLE
Broken in Chromium?

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/airspace-visualizer#34]
It doesn't seem to do anything when dropping a file.

**Comment by sbrodehl** [comment]
Tested with `Chromium Version 119.0.6045.159` today and had no issues.

**Comment by dbrgn** [comment]
Interesting, then it might be a Linux/Wayland issue. I'll have to investigate why drag&drop seems to work on other websites in my Chromium, but not in the airspace visualizer.
